#!/usr/bin/with-contenv bash

export HOME=/config

if [ "${PROXY_ENABLED}" != "true" ]; then
    s6-svc -d .
    exit 0
fi

command="pproxy -l http://0.0.0.0:${PROXY_PORT:-8008}"
if [[ -n ${PROXY_USER:-} ]] && [[ -n ${PROXY_PASS:-} ]]; then
    command="$command#${PROXY_USER}:${PROXY_PASS}"
fi
if [ "${GT_ENABLED}" = "true" ]; then
    command="$command -r http://127.0.0.1:${GT_PORT:-21000}"
fi
command="$command --auth ${PROXY_AUTHTIME:-0}${PROXY_VERBOSE+ -v}"

echo "*** executing => $command"
exec s6-setuidgid abc $command
